Repository DaITssu/daitssu-client, pull requests merged in 2023-12, with the labels that each got.

#148 [#136] 메인화면 API 연결
  src/apis/axiosInstance.ts
  src/apis/mainAPIs.ts
  src/components/Home/NoticeFunSystem/NoticeFunSystem.tsx
  src/components/Home/PopularPosts/PopularPosts.styles.ts
  src/components/main/index.tsx
Labels: feat :wrench:

#152 [#151] 서비스 공지사항 디자인 수정
  src/components/community/list/CommunityList.stories.tsx
  src/components/community/list/CommunityList.style.ts
  src/components/community/list/CommunityList.tsx
  src/components/community/list/CommunityListItem.stories.tsx
  src/components/community/list/CommunityListItem.tsx
  src/components/myPage/ServiceNotice/ServiceNoticeItem.styles.ts
  src/components/myPage/ServiceNotice/ServiceNoticeList.styles.ts
  src/components/myPage/ServiceNotice/info/ServiceNoticeInfo.styles.ts
  src/components/mypage/ServiceNotice/ServiceNoticeItem.tsx
  src/components/mypage/ServiceNotice/info/ServiceNoticeInfo.tsx
Labels: refactor :toolbox:

#154 [#153] PR 올릴 경우, 자동으로 build 실행
  .github/CODEOWNERS
  .github/workflows/pull_request_action.yml
  src/components/Calendar/AlarmSetting/AlarmSetting.tsx
  src/components/Calendar/EditEventModal/EditEventModal.tsx
  src/components/Calendar/Subject/Subject.stories.tsx
  src/components/Calendar/Subject/Subject.style.ts
  src/components/Calendar/Subject/Subject.tsx
  src/components/Calendar/Subject/index.ts
  src/components/Calendar/SubjectContents/SubjectContents.stories.tsx
  src/components/Calendar/SubjectContents/SubjectContents.style.ts
  src/components/Calendar/SubjectContents/SubjectContents.tsx
  src/components/Calendar/SubjectContents/index.ts
  src/components/Calendar/SubjectList/SubjectList.stories.tsx
  src/components/Calendar/SubjectList/SubjectList.style.ts
  src/components/Calendar/SubjectList/SubjectList.tsx
  src/components/Calendar/SubjectList/index.ts
  src/components/Calendar/SubjectTitle/SubjectTitle.stories.tsx
  src/components/Calendar/SubjectTitle/SubjectTitle.style.ts
  src/components/Calendar/SubjectTitle/SubjectTitle.tsx
  src/components/Calendar/SubjectTitle/index.ts
  src/components/Home/NoticeFunSystem/NoticeFunSystem.stories.tsx
  src/components/community/community_writing/ImageInputBox/IconBox/IconBox.tsx
  src/components/community/community_writing/ImageInputBox/ImageInputBox.tsx
  src/components/community/list/CommunityList.tsx
  src/components/myPage/Post/MyComment.tsx
  src/components/myPage/Post/MyPost.stories.tsx
  src/components/myPage/Post/MyPost.tsx
  src/components/myPage/Post/Mypost.style.tsx
  src/components/myPage/Post/Tab/MyPostsTab.stories.tsx
  src/components/myPage/Post/Tab/MyPostsTab.style.tsx
  src/components/myPage/Post/Tab/MyPostsTab.tsx
  src/components/myPage/ServiceNotice/ServiceNoticeItem.stories.tsx
  src/components/myPage/ServiceNotice/ServiceNoticeItem.tsx
  src/components/myPage/ServiceNotice/ServiceNoticeList.stories.tsx
  src/components/myPage/ServiceNotice/ServiceNoticeList.tsx
  src/components/myPage/ServiceNotice/info/ServiceNoticeInfo.stories.tsx
  src/components/myPage/ServiceNotice/info/ServiceNoticeInfo.tsx
  src/components/myPage/agree/Agree.stories.tsx
  src/components/myPage/agree/Agree.style.ts
  src/components/myPage/agree/Agree.tsx
  src/components/myPage/agree/info/AgreeInfo.stories.tsx
  src/components/myPage/agree/info/AgreeInfo.style.ts
  src/components/myPage/agree/info/AgreeInfo.tsx
  src/components/myPage/agree/info/AgreeText.tsx
  src/components/notice/NoticeItem.stories.tsx
  src/components/notice/NoticeList.stories.tsx
  src/components/notice/anouncement/Anouncement.tsx
  src/pages/my/agree/index.page.tsx
  src/pages/my/agree/info/index.page.tsx
  src/pages/my/blockAccount/index.page.tsx
  src/pages/my/post/index.page.tsx
  src/pages/my/setting/index.page.tsx
  src/pages/my/withdrawal/index.page.tsx
  src/types/course.ts
Labels: fix :brain:

#155 [#129] 공지사항, 펀시스템 상세정보 및 댓글 API 연결
  src/apis/communityAPIS.ts
  src/apis/funsystemAPIs.ts
  src/apis/noticeAPIS.ts
  src/apis/noticeAPIs.ts
  src/components/Home/NoticeFunSystemTab/NoticeFunSystemList.tsx
  src/components/common/Comment/Comment.style.ts
  src/components/common/Comment/Comment.tsx
  src/components/community/info/CommunityInfo.tsx
  src/components/notice/FunSystemList.tsx
  src/components/notice/NoticeItem.stories.tsx
  src/components/notice/NoticeItem.tsx
  src/components/notice/NoticeList.tsx
  src/components/notice/info/NoticeInfo.style.ts
  src/components/notice/info/NoticeInfo.tsx
  src/components/noticeInfo/NoticeInfo.tsx
  src/pages/funsystem/[id].page.tsx
  src/pages/notice/[id].page.tsx
  src/pages/notice/info/index.page.tsx
  src/types/NoticeFunsystem.ts
Labels: feat :wrench:

#157 [#156] 공지사항/펀시스템 상세정보 page id 리팩토링
  src/components/notice/info/NoticeInfo.tsx
Labels: refactor :toolbox:
