Repository DaITssu/daitssu-client, pull requests merged in 2023-10, with the labels that each got.

#107 [#105] 로그인 후 이용 가능 모달 UI 컴포넌트 구현
  src/components/common/Button/Button.styles.ts
  src/components/login/NeedLoginModal/NeedLoginModal.stories.tsx
  src/components/login/NeedLoginModal/NeedLoginModal.styles.ts
  src/components/login/NeedLoginModal/NeedLoginModal.tsx
Labels: feat :wrench:

#113 [#112] 랜딩페이지 네이비게이션바 스크롤에 따라 렌더링
  src/components/common/Navbar/NavItem.tsx
  src/components/common/Navbar/NavigationBar.style.ts
  src/components/common/Navbar/NavigationBar.tsx
  src/components/main/index.tsx
  src/hooks/useNavbar.ts
  src/pages/layout/index.tsx
Labels: feat :wrench:

#120 [#119] NavigationBar props 관련 에러 수정
  src/components/common/Navbar/NavigationBar.tsx
Labels: fix :brain:

#115 [#114] Calendar 과제 알림 스크린 추가
  src/components/Calendar/AlarmSetting/AlarmSetting.stories.tsx
  src/components/Calendar/AlarmSetting/AlarmSetting.styles.tsx
  src/components/Calendar/AlarmSetting/AlarmSetting.tsx
  src/components/Calendar/AlarmSetting/index.ts
  src/components/Calendar/Calendar/Calendar.stories.tsx
  src/components/Calendar/Calendar/Calendar.tsx
  src/components/Calendar/Calendar/WeekBlock/WeekBlock.tsx
  src/components/Calendar/CalendarScreen/CalendarButton/CalendarButton.styles.tsx
  src/components/Calendar/CalendarScreen/CalendarScreen.stories.tsx
  src/components/Calendar/CalendarScreen/CalendarScreen.tsx
  src/components/Calendar/EditEventModal/EditEventModal.stories.tsx
  src/components/calendar/Subject/Subject.stories.tsx
  src/components/calendar/SubjectContents/SubjectContents.stories.tsx
  src/components/calendar/SubjectContents/SubjectContents.tsx
  src/components/calendar/SubjectList/SubjectList.stories.tsx
  src/components/calendar/SubjectTitle/SubjectTitle.stories.tsx
  src/components/common/Status/Status.styles.ts
  src/pages/calendar/alarm/index.page.tsx
Labels: feat :wrench:

#117 [#116] 공통 스타일로 변경
  src/components/common/Comment/Comment.style.ts
  src/components/common/Comment/CommentInput/CommentInput.styles.ts
  src/components/common/Comment/CommentInput/CommentInput.tsx
  src/components/myPage/Scrap/ScrapList.style.tsx
  src/components/mypage/Post/Mypost.style.tsx
  src/components/mypage/agree/Agree.style.ts
  src/components/notice/info/NoticeInfo.style.ts
Labels: style 💄

#126 [#125] axios 예제 코드 추가
  package.json
  src/apis/axiosInstance.ts
  src/apis/courseAPIS.ts
  src/apis/userAPIS.ts
  src/pages/test/index.page.tsx
  tsconfig.json
  yarn.lock
Labels: feat :wrench:

#123 [#121] 모바일 뷰 관련 작업
  src/pages/_app.page.tsx
  src/pages/index.page.tsx
Labels: feat :wrench:

#122 [#118] 공지사항 디자인 깨짐 수정
  src/components/notice/Layout.tsx
  src/components/notice/TopTab.tsx
  src/components/notice/anouncement/Anouncement.style.ts
  src/components/notice/anouncement/SearchBar.style.ts
  src/components/notice/anouncement/SearchBar.tsx
  src/components/notice/anouncement/SelectButton.style.ts
  src/components/notice/anouncement/SelectButton.tsx
  src/pages/notice/index.page.tsx
  src/styles/constants/TopTab.style.ts
Labels: fix :brain:

#111 [#91] 회원가입 페이지 구현 (0-4-2, 0-4-3, 0-4-4)
  src/components/Register/Register.stories.tsx
  src/components/Register/Register.styles.ts
  src/components/Register/Register.tsx
  src/components/Register/TOS/TOS.stories.tsx
  src/components/Register/TOS/TOS.styles.ts
  src/components/Register/TOS/TOS.tsx
  src/components/Register/TosItems/TosItem.stories.tsx
  src/components/Register/TosItems/TosItem.styles.ts
  src/components/Register/TosItems/TosItem.tsx
  src/pages/register/index.page.tsx
Labels: feat :wrench:
