Repository DaITssu/daitssu-client, pull requests merged in 2023-11, with the labels that each got.

#135 [#134] 마이페이지 이용약관 모달로 변경
  src/components/Register/Register.styles.ts
  src/components/Register/Register.tsx
  src/components/Register/TOS/TOS.styles.ts
  src/components/Register/TOS/TOS.tsx
  src/components/Register/TosItems/TosItem.styles.ts
  src/components/mypage/agree/Agree.style.ts
  src/components/mypage/agree/Agree.tsx
  src/components/mypage/agree/AgreeText.tsx
Labels: fix :brain:, style 💄

#140 [#139] 공지사항/구독 디자인 수정
  src/components/NoticeItem.tsx
  src/components/NoticeList.tsx
  src/components/TopBar.tsx
  src/components/TopTab.tsx
  src/components/notice/NoticeItem.styles.ts
  src/components/notice/NoticeItem.tsx
  src/components/notice/NoticeList.styles.ts
  src/components/notice/NoticeList.tsx
  src/components/notice/TopBar.tsx
  src/components/notice/TopTab.styles.ts
  src/components/notice/TopTab.tsx
  src/components/notice/anouncement/SearchBar.styles.ts
  src/components/notice/anouncement/SearchBar.tsx
  src/components/notice/anouncement/SelectButton.style.ts
  src/components/notice/anouncement/SelectButton.tsx
  src/pages/notice/index.page.tsx
Labels: refactor :toolbox:, fix :brain:

#142 [#141] 공지사항/펀시스템 (4-1,4-2) API 연결
  src/apis/noticeAPIS.ts
  src/components/notice/CategoryMapping.tsx
  src/components/notice/NoticeItem.tsx
  src/components/notice/NoticeList.tsx
  src/components/notice/TopTab.tsx
  src/components/notice/anouncement/SearchBar.tsx
  src/components/notice/anouncement/SelectButton.tsx
Labels: feat :wrench:, refactor :toolbox:

#147 [#146] 헤더 검색창 API 연결 (figma 1-2-x)
  src/components/Home/NoticeFunSystemTab/LineSearchBar/LineSearchBar.styles.ts
  src/components/Home/NoticeFunSystemTab/LineSearchBar/LineSearchBar.tsx
  src/components/Home/NoticeFunSystemTab/NoticeFunSystemTab.styles.tsx
  src/components/Home/NoticeFunSystemTab/NoticeFunSystemTab.tsx
  src/components/Layout.tsx
  src/components/common/Header/Header.tsx
  src/components/community/list/CommunityList.tsx
  src/components/notice/FunSystemList.tsx
  src/components/notice/NoticeList.styles.ts
  src/components/notice/NoticeList.tsx
  src/components/notice/TopTab.tsx
  src/pages/community/index.page.tsx
Labels: feat :wrench:, fix :brain:

#138 [#137] 캘린더 스크린 API 연결
  src/apis/courseAPIS.ts
  src/components/Calendar/Calendar/Calendar.tsx
  src/components/Calendar/CalendarScreen/CalendarScreen.tsx
  src/components/Calendar/EditEventModal/EditEventModal.styles.tsx
  src/components/Calendar/EditEventModal/EditEventModal.tsx
  src/pages/calendar/alarm/index.page.tsx
  src/pages/calendar/index.page.tsx
  src/types/course.ts
Labels: feat :wrench:
