Repository DaITssu/daitssu-client, pull requests merged in 2023-07, with the labels that each got.

#5 [#3] design tokens & Common Components
  .gitignore
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/Button.styles.ts
  src/components/common/Button/Button.tsx
  src/components/common/Button/index.ts
  src/components/common/Category/Category.stories.tsx
  src/components/common/Category/Category.styles.ts
  src/components/common/Category/Category.tsx
  src/components/common/Category/index.ts
  src/components/common/Status/Status.stories.tsx
  src/components/common/Status/Status.styles.ts
  src/components/common/Status/Status.tsx
  src/components/common/Status/index.ts
  src/components/common/Test/Test.tsx
  src/styles/constants/colors.ts
  src/styles/constants/textStyles.ts
  src/styles/font.css
  src/styles/index.css
  yarn.lock
Labels: feat :wrench:

#15 [#14] 공지사항 상세조회 및 댓글 뷰 완성
  public/noticeInfo/attach.svg
  public/noticeInfo/backarrow.svg
  public/noticeInfo/calendar.svg
  public/noticeInfo/download.svg
  public/noticeInfo/kakao.svg
  public/noticeInfo/message.svg
  public/noticeInfo/profile.svg
  public/noticeInfo/report.svg
  public/noticeInfo/share.svg
  public/noticeInfo/shareClick.svg
  public/noticeInfo/url.svg
  public/noticeInfo/watch.svg
  src/components/noticeInfo/NoticeInfo.tsx
Labels: feat :wrench:

#18 [#17] 공지사항 목록 및 탭 뷰 구현
  public/images/Rectangle_242.png
  public/images/alarm_icon.png
  public/images/notice_status.png
  public/images/round_rectangle_item.png
  public/images/search_icon.png
  public/images/view_icon.png
  src/components/Layout.tsx
  src/components/NoticeItem.tsx
  src/components/NoticeList.tsx
  src/components/TopBar.tsx
  src/components/TopTab.tsx
  src/styles/Top.module.css
Labels: feat :wrench:

#20 [#3] svg 아이콘 추가
  public/assets/icon/Arrow/DownBigArrow.svg
  public/assets/icon/Arrow/DownSmallArrow.svg
  public/assets/icon/Arrow/LeftBigArrow.svg
  public/assets/icon/Arrow/LeftSmallArrow.svg
  public/assets/icon/Arrow/RightBigArrow.svg
  public/assets/icon/Arrow/RightBigArrow1.svg
  public/assets/icon/Arrow/RightBigArrow2.svg
  public/assets/icon/Arrow/RightSmallArrow.svg
  public/assets/icon/Arrow/UpBigArrow.svg
  public/assets/icon/Arrow/UpSmallArrow.svg
  public/assets/icon/CheckBox/BlueCheckedBox.svg
  public/assets/icon/CheckBox/DefaultCheckBox.svg
  public/assets/icon/CheckBox/GrayCheckedBox.svg
  public/assets/icon/Icon18/ Sue.svg
  public/assets/icon/Icon18/Ben.svg
  public/assets/icon/Icon18/Close.svg
  public/assets/icon/Icon18/GrayCircleCancel.svg
  public/assets/icon/Icon18/SmallComment.svg
  public/assets/icon/Icon18/SmallHits.svg
  public/assets/icon/Icon18/Url.svg
  public/assets/icon/Icon18/WhiteCircleCancel.svg
  public/assets/icon/Icon24/AttachedFile.svg
  public/assets/icon/Icon24/CalenderUpdate.svg
  public/assets/icon/Icon24/Comment.svg
  public/assets/icon/Icon24/Correction.svg
  public/assets/icon/Icon24/Download.svg
  public/assets/icon/Icon24/Hits.svg
  public/assets/icon/Icon24/Menu.svg
  public/assets/icon/Icon24/Share.svg
  public/assets/icon/LectureAssignment/Assignment.svg
  public/assets/icon/LectureAssignment/Comment.svg
  public/assets/icon/LectureAssignment/Video.svg
  public/assets/icon/Liked/DefaultLiked.svg
  public/assets/icon/Liked/FilledLiked.svg
  public/assets/icon/Notification/NewNotification.svg
  public/assets/icon/Notification/Notification.svg
  public/assets/icon/Radio/CheckedRadio.svg
  public/assets/icon/Radio/DefaultRadio.svg
  public/assets/icon/Scrap/DefaultScrap.svg
  public/assets/icon/Scrap/FilledScrap.svg
  public/assets/icon/Search/BlueSearch.svg
  public/assets/icon/Search/GraySearch.svg
  public/assets/icon/Shape/Ellipse.svg
  public/assets/icon/Shape/Triangle.svg
  public/assets/icon/Shape/X.svg
  public/assets/icon/SubscribeList/Post.svg
  public/assets/icon/SubscribeList/Scrap.svg
  public/assets/icon/SubscribeList/Setting.svg
  public/assets/icon/SubscribeList/SubscribeList.svg
  src/components/common/Status/Status.stories.tsx
Labels: feat :wrench:, fix :brain:

#19 fix:storybook 절대경로 문제 해결
  .storybook/main.ts
  package.json
  public/assets/alert_icon/alert_active.svg
  public/assets/alert_icon/alert_default.svg
  public/assets/assignment_icon/assignmnet_default.svg
  public/assets/attendance_icon/absent.svg
  public/assets/attendance_icon/attend.svg
  public/assets/attendance_icon/late.svg
  public/assets/calendar_icon/calendar_black.svg
  public/assets/calendar_icon/calendar_primary.svg
  public/assets/checkbox_icon/check_black.svg
  public/assets/checkbox_icon/check_primary.svg
  public/assets/comment_icon/comment_default.svg
  public/assets/heart_icon/heart_default.svg
  public/assets/heart_icon/heart_primary.svg
  public/assets/nav_icon/announcement/announcement_black.svg
  public/assets/nav_icon/announcement/announcement_primary.svg
  public/assets/nav_icon/calendar/calendar_black.svg
  public/assets/nav_icon/calendar/calendar_primary.svg
  public/assets/nav_icon/community/community_black.svg
  public/assets/nav_icon/community/community_primary.svg
  public/assets/nav_icon/home/home_black.svg
  public/assets/nav_icon/home/home_primary.svg
  public/assets/nav_icon/my/my_black.svg
  public/assets/nav_icon/my/my_primary.svg
  public/assets/scrap_icon/scrap_black.svg
  public/assets/scrap_icon/scrap_primary.svg
  public/assets/search_icon/search_black.svg
  public/assets/search_icon/search_primary.svg
  public/assets/subscribe_icon/subscribe_article.svg
  public/assets/subscribe_icon/subscribe_scrap.svg
  public/assets/subscribe_icon/subscribe_setting.svg
  public/assets/subscribe_icon/subscribe_star.svg
  public/assets/video_icon/video.svg
  src/components/Test/Test.stories.tsx
  src/components/Test/Test.style.ts
  src/components/Test/Test.tsx
  tsconfig.json
  yarn.lock
Labels: fix :brain:

#21 fix:아이콘 최종 수정
  public/assets/alert_icon/alert_active.svg
  public/assets/alert_icon/alert_default.svg
  public/assets/assignment_icon/assignmnet_default.svg
  public/assets/attendance_icon/absent.svg
  public/assets/attendance_icon/attend.svg
  public/assets/attendance_icon/late.svg
  public/assets/calendar_icon/calendar_black.svg
  public/assets/calendar_icon/calendar_primary.svg
  public/assets/checkbox_icon/check_black.svg
  public/assets/checkbox_icon/check_primary.svg
  public/assets/comment_icon/comment_default.svg
  public/assets/heart_icon/heart_default.svg
  public/assets/heart_icon/heart_primary.svg
  public/assets/nav_icon/announcement/announcement_black.svg
  public/assets/nav_icon/announcement/announcement_primary.svg
  public/assets/nav_icon/calendar/calendar_black.svg
  public/assets/nav_icon/calendar/calendar_primary.svg
  public/assets/nav_icon/community/community_black.svg
  public/assets/nav_icon/community/community_primary.svg
  public/assets/nav_icon/home/home_black.svg
  public/assets/nav_icon/home/home_primary.svg
  public/assets/nav_icon/my/my_black.svg
  public/assets/nav_icon/my/my_primary.svg
  public/assets/scrap_icon/scrap_black.svg
  public/assets/scrap_icon/scrap_primary.svg
  public/assets/search_icon/search_black.svg
  public/assets/search_icon/search_primary.svg
  public/assets/subscribe_icon/subscribe_article.svg
  public/assets/subscribe_icon/subscribe_scrap.svg
  public/assets/subscribe_icon/subscribe_setting.svg
  public/assets/subscribe_icon/subscribe_star.svg
  public/assets/video_icon/video.svg
  src/components/Test/Test.stories.tsx
  src/components/Test/Test.style.ts
  src/components/Test/Test.tsx
Labels: fix :brain:

#28 [#27] CSS 스타일 변환, 버튼 이벤트 수정
  package-lock.json
  package.json
  src/components/NoticeItem.tsx
  src/components/TopTab.tsx
  src/components/notice/Layout.tsx
  src/components/notice/NoticeItem.tsx
  src/components/notice/NoticeList.tsx
  src/components/notice/TopBar.tsx
  src/components/notice/TopTab.tsx
  src/styles/constants/NoticeItem.style.ts
  src/styles/constants/NoticeList.style.ts
  src/styles/constants/TopTab.style.ts
  tsconfig.json
  yarn.lock
Labels: refactor :toolbox:

#24 [#23] 댓글 공통 컴포넌트로 분류
  src/components/common/Comment/Comment.style.ts
  src/components/common/Comment/Comment.tsx
  src/components/common/Comment/CommentInput/CommentInput.styles.ts
  src/components/common/Comment/CommentInput/CommentInput.tsx
  src/components/common/Comment/CommentInput/index.ts
  src/components/common/Comment/index.ts
  src/components/noticeInfo/NoticeInfo.style.ts
  src/components/noticeInfo/NoticeInfo.tsx
  src/pages/noticeInfo/index.page.tsx
Labels: feat :wrench:

#33 [#30] 공지사항구독 페이지 합치기
  src/components/notice/Layout.tsx
  src/components/notice/NoticeItem.tsx
  src/components/notice/NoticeList.tsx
  src/components/notice/TopTab.tsx
  src/components/notice/anouncement/Anouncement.style.ts
  src/components/notice/anouncement/Anouncement.tsx
  src/components/notice/anouncement/SearchBar.stories.tsx
  src/components/notice/anouncement/SearchBar.tsx
  src/components/notice/anouncement/SelectButton.tsx
  src/components/notice/anouncement/index.ts
  src/components/notice/info/NoticeInfo.style.ts
  src/components/notice/info/NoticeInfo.tsx
  src/pages/notice/index.page.tsx
  src/pages/notice/info/index.page.tsx
  src/styles/constants/TopTab.style.ts
Labels: refactor :toolbox:
