Repository DaITssu/daitssu-client, pull requests merged in 2024-03, with the labels that each got.

#191 [#189] style: favoico, title 적용
  public/favicon.ico
  src/pages/_app.page.tsx
Labels: style 💄

#186 [#184] 로그인/회원가입시 에러 코드에 따라 분기, 토큰 refresh 에러 수정, 회원가입 API 연결
  src/apis/authAPIS.ts
  src/components/Register/Register.styles.ts
  src/components/Register/Register.tsx
  src/components/Register/TosItems/TosItem.styles.ts
  src/components/common/InputBox/InputBox.styles.ts
  src/components/landing/AuthContent/AuthContent.style.ts
  src/components/landing/AuthContent/AuthContent.tsx
  src/components/landing/index.tsx
  src/components/login/FindAccount/FindAccountLayout.tsx
  src/components/login/LoginLayout/LoginLayout.tsx
  src/components/myPage/withdrawal/withdrawal.style.ts
  src/components/myPage/withdrawal/withdrawal.tsx
  src/hooks/useCheckLogin.ts
  src/hooks/useValidUser.ts
  src/pages/_app.page.tsx
  src/types/Auth.ts
Labels: fix :brain:

#188 [#177] feat: 공지사항/펀시스템/커뮤니티 댓글 작성 및 삭제
  src/apis/communityAPIS.ts
  src/apis/funsystemAPIs.ts
  src/apis/noticeAPIs.ts
  src/components/common/Comment/CommentInput/CommentInput.tsx
  src/components/community/info/CommunityInfo.tsx
  src/components/community/list/CommunityList.tsx
  src/components/myPage/Comment/CommentList.tsx
  src/components/myPage/Comment/MyComment.tsx
  src/components/myPage/Post/MyPost.tsx
  src/components/myPage/Post/Tab/MyPostsTab.tsx
  src/components/notice/info/NoticeInfo.tsx
  src/utils/EngToKor.ts
Labels: feat :wrench:

#194 [#192] 상세정보 수정
  src/components/common/Header/UtilityHeader.tsx
  src/components/myPage/home/home.tsx
  src/components/notice/info/NoticeInfo.tsx
Labels: fix :brain:

#198 [#190] 이용약관 추가
  src/components/Register/TOS/TOS.styles.ts
  src/components/Register/TOS/TOS.tsx
Labels: feat :wrench:

#197 [#196] 커뮤니티 api 연결 수정
  src/apis/communityAPIS.ts
  src/components/community/list/CommunityList.style.ts
  src/components/community/list/CommunityList.tsx
  src/components/community/list/CommunityListItem.stories.tsx
  src/components/community/list/CommunityListItem.style.ts
  src/components/community/list/CommunityListItem.tsx
  src/pages/community/index.page.tsx
Labels: fix :brain:

#193 [#173] 공지사항 펀시스템 여러 수정
  src/apis/noticeAPIs.ts
  src/components/notice/FunSystemList.tsx
  src/components/notice/NoticeList.styles.ts
  src/components/notice/NoticeList.tsx
  src/components/notice/TopTab.styles.ts
  src/components/notice/anouncement/SelectButton.style.ts
  src/components/notice/anouncement/SelectButton.tsx
  src/pages/funsystem/index.page.tsx
  src/pages/notice/index.page.tsx
Labels: fix :brain:

#208 [#207] 버튼 padding 수정
  src/components/notice/anouncement/SelectButton.style.ts
Labels: fix :brain:
