Repository DaITssu/daitssu-client, pull requests merged in 2024-01, with the labels that each got.

#162 [#161] 상세정보 반응형으로 수정
  src/components/common/Comment/CommentInput/CommentInput.styles.ts
  src/components/notice/info/NoticeInfo.style.ts
Labels: style 💄

#165 [#164] 레이아웃 관련 스타일 수정
  src/components/common/Header/Header.tsx
  src/components/landing/Landing.styles.ts
  src/styles/globals.css
Labels: fix :brain:, style 💄

#166 [#150] 서비스 공지사항 (figma 6-8) api 연결 및 수정
  src/apis/serviceNoticeAPIS.ts
  src/components/myPage/ServiceNotice/ServiceNoticeItem.stories.tsx
  src/components/myPage/ServiceNotice/ServiceNoticeItem.tsx
  src/components/myPage/ServiceNotice/ServiceNoticeList.stories.tsx
  src/components/myPage/ServiceNotice/ServiceNoticeList.styles.ts
  src/components/myPage/ServiceNotice/ServiceNoticeList.tsx
  src/components/myPage/ServiceNotice/info/ServiceNoticeInfo.stories.tsx
  src/components/myPage/ServiceNotice/info/ServiceNoticeInfo.tsx
  src/pages/my/serviceNotice/index.page.tsx
  src/pages/my/serviceNotice/info/index.page.tsx
Labels: feat :wrench:

#158 [#133] 로그인 api 연결, 관련 UI 구현
  public/images/loader.png
  src/apis/authAPIS.ts
  src/apis/axiosInstance.ts
  src/components/Home/NoticeFunSystem/NoticeFunSystem.tsx
  src/components/Register/Register.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Loader/Loader.stories.tsx
  src/components/common/Loader/Loader.style.ts
  src/components/common/Loader/Loader.tsx
  src/components/login/FindAuth/FindAuth.styles.ts
  src/components/login/FindAuth/FindAuth.tsx
  src/components/login/LoginErrorModal/LoginErrorModal.styles.ts
  src/components/login/LoginErrorModal/LoginErrorModal.tsx
  src/components/login/LoginLayout/LoginLayout.tsx
  src/components/login/LoginProcess/LoginProcess.styles.ts
  src/components/login/LoginProcess/LoginProcess.tsx
  src/hooks/useAxiosInterceptor.ts
  src/pages/index.page.tsx
  src/pages/layout/index.tsx
  src/states/authAtom.ts
  src/states/userNavAtom.ts
  src/styles/constants/textStyles.ts
  src/types/Auth.ts
Labels: feat :wrench:

#170 [#169] 공지사항 펀시스템 에러 수정
  src/components/notice/FunSystemList.tsx
  src/components/notice/NoticeList.tsx
  src/components/notice/TopTab.styles.ts
  src/components/notice/TopTab.tsx
  src/components/notice/anouncement/SearchBar.styles.ts
Labels: fix :brain:
